# Generated by Django 4.2.6 on 2025-08-30 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_product_is_flash_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_flash_sale',
            field=models.BooleanField(default=False),
        ),
    ]
