# Generated by Django 4.2.6 on 2025-09-01 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='athour',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='athour/cover'),
        ),
        migrations.AddField(
            model_name='athour',
            name='facebook',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='athour',
            name='location',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='athour',
            name='pio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='athour',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='athour/profile'),
        ),
        migrations.AddField(
            model_name='athour',
            name='slug',
            field=models.SlugField(blank=True, max_length=150, unique=True),
        ),
        migrations.AddField(
            model_name='athour',
            name='twitter',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='tag_post',
            field=models.ManyToManyField(to='website.tag'),
        ),
    ]
