# Generated by Django 4.2.6 on 2025-09-01 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_tag_athour_cover_image_athour_facebook_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Athour',
            new_name='Author',
        ),
    ]
