# Generated by Django 4.2.6 on 2025-09-03 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_alter_tag_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tag_post',
        ),
        migrations.AddField(
            model_name='post',
            name='tag_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.tag'),
        ),
    ]
