# Generated by Django 4.2.6 on 2025-09-04 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_remove_post_tag_post_post_tag_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(blank=True, max_length=300, null=True)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='about/image1')),
                ('description1', models.TextField(blank=True, null=True)),
                ('image2', models.ImageField(blank=True, null=True, upload_to='about/image2')),
                ('description2', models.TextField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('facebook', models.CharField(blank=True, max_length=1000, null=True)),
                ('twitter', models.CharField(blank=True, max_length=1000, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('slug', models.SlugField(blank=True, max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('content', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, max_length=150, unique=True)),
            ],
        ),
    ]
